rails-basics-ru/nested-resources/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#index'

  # BEGIN
  scope module: :web do
    resources :posts, only: [:index]

    resources :posts, except: [:index] do
      resources :comments, only: %i[index new create]
    end

    resources :posts, except: [:index], shallow: true do
      resources :comments, only: %i[show edit update destroy]
    end
  end
  # END
end

rails-basics-ru/nested-resources/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :body, presence: true
end

rails-basics-ru/nested-resources/app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  # BEGIN
  has_many :comments, dependent: :destroy
  # END

  validates :title, presence: true
  validates :body, length: { maximum: 500 }
end

rails-basics-ru/nested-resources/app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
end

rails-basics-ru/nested-resources/app/controllers/web/comments_controller.rb
module Web
  class CommentsController < ApplicationController
    before_action :set_post, only: %i[index new create]
    before_action :set_comment, only: %i[edit update destroy]

    def index
      @comments = @post.comments
    end

    def show; end

    def new
      @comment = @post.comments.build
    end

    def edit
    end

    def create
      @comment = @post.comments.build(comment_params)

      if @comment.save
        redirect_to post_path(@post), notice: 'Comment was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @comment.update(comment_params)
        redirect_to posts_url, notice: 'Comment was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @comment.destroy

      redirect_to posts_url, notice: 'Comment was successfully destroyed.'
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.permit(:body, :post_id)
    end
  end
end

rails-basics-ru/nested-resources/app/controllers/web/posts_controller.rb
# frozen_string_literal: true

module Web
  class PostsController < ApplicationController
    def index
      @posts = Post.all
    end

    def show
      @post = Post.find params[:id]
    end

    def new
      @post = Post.new
    end

    def edit
      @post = Post.find params[:id]
    end

    def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      @post = Post.find params[:id]

      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @post = Post.find params[:id]

      @post.destroy

      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
  end
end

rails-basics-ru/nested-resources/app/helpers/comments_helper.rb
module CommentsHelper
end

rails-basics-ru/nested-resources/app/views/web/posts/index.html.slim
= content_for :title do
  = 'Posts'

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope = 'col' } #
      th{ scope = 'col' } Title
      th

  tbody
    - @posts.each_with_index do |post, i|
      tr
        th{ scope = 'row' } = i + 1
        td = post.title
        td.d-flex
          .me-4 = link_to 'Show', post
          .me-4 = link_to 'Edit', edit_post_path(post)
          = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

= link_to 'New Post', new_post_path, class: 'btn btn-primary'

rails-basics-ru/nested-resources/app/views/web/posts/show.html.slim
- content_for :title do
  = @post.title
p
  strong.me-2 Body:
  = @post.body
/ BEGIN

= link_to 'Leave comment', new_post_comment_path(@post), class: 'btn btn-outline-primary'

- @post.comments.each do |comment|
  div
    span.mr-4= comment[:body]
    span= link_to 'Edit', edit_comment_path(comment), class: 'btn btn-outline-primary mr-2'
    span= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary mr-2'
/ END
hr

.d-flex
  = link_to 'Edit', edit_post_path(@post), class: 'btn btn-outline-primary mr-2'
  = link_to 'Back', :back, class: 'btn btn-outline-primary'